version: "3.6"

services:
  mongodb:
    container_name: mongodb
    image: mongodb
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: '2g'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - default_net
    volumes:
      - 'mongodb-data:/data/db'
      - 'mongodb-config:/data/configdb'
    command: --bind_ip_all --replSet rs0 --keyFile keyFile.pem

  redis:
    container_name: redis
    image: redis
    restart: always
    mem_limit: '2g'
    ports:
      - 6379:6379
    networks:
      - default_net
    volumes:
      - 'redis-data:/data'
    command: redis-server --requirepass password

volumes:
  mongodb-data:
    name: mongodb-data
  mongodb-config:
    name: mongodb-config
  redis-data:
    name: redis-data

networks:
  default_net:
    external: true
    name: default_net